---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE}
library(tidyverse)
library(readr)
library(janitor)
```

```{r, message = FALSE}
#cal data was tidied in google sheets
cal_data <- read_csv("~/chem313/lcms_levoglucosan/data/cal_new.csv")

field_data <- read_csv("~/chem313/lcms_levoglucosan/data/field_new.csv")
```

```{r}
#calibration curve
mod <- lm(cal_data$peak_area ~ cal_data$conc)
slope <- mod$coefficients[2]
intercept <- mod$coefficients[1]
slope_std <- summary(mod)$coefficients[2,2]
intercept_std <- summary(mod)$coefficients[1,2]
equation <- tibble(slope, slope_std, intercept, intercept_std)
cal <- rbind(equation)
cal
summary(mod)

ggplot(data = cal_data, mapping = aes(x = conc, y = peak_area)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color ="red") +
  labs(x = "[Levoglucosan] (ug/mL)",
       y = "Peak Area",
       title = "Calibration for Levoglucosan") +
  theme_bw()


```

```{r}
#finding concentration and propagating error
field_data <- field_data %>%
  mutate(conc = (field_data$peak_area - cal$intercept)/cal$slope,
conc_e = conc*sqrt((cal$intercept_std/cal$intercept)^2 + (cal$slope_std/cal$slope)^2))

```

```{r}
#comparing east and west data over all time
east_data <- field_data %>%
  filter(str_detect(sample, "E"))
west_data <- field_data %>%
  filter(str_detect(sample, "W"))

var.test(west_data$peak_area, east_data$peak_area) #difference is significant

t.test(west_data$peak_area, east_data$peak_area, mu = 0, paired = TRUE, var.equal = FALSE)
#difference is not significant
```
```{r}
data1750 <- field_data %>%
  filter(str_detect(sample, "1750"))
data1950 <- field_data %>%
  filter(str_detect(sample, "1950"))
data2020 <- field_data %>%
  filter(str_detect(sample, "2020"))

#f test to compare standard deviations
var.test(data1950$peak_area, data1750$peak_area) #not significant
var.test(data2020$peak_area, data1750$peak_area) #significant
var.test(data2020$peak_area, data1950$peak_area) #significant

#unpaired t test for similar variances
t.test(data1750$peak_area, data1950$peak_area, mu = 0, paired = FALSE, var.equal = TRUE) #significantly different (2.415 > 2.228)

#paired t test for different variances
t.test(data2020$peak_area, data1750$peak_area, mu = 0, paired = TRUE, var.equal = FALSE)
#significantly different (2.7514 > 2.571)
t.test(data2020$peak_area, data1950$peak_area, mu = 0, paired = TRUE, var.equal = FALSE)
#significantly different (3.071 > 2.571)
```

